apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: petshop
  name: petshop-Deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: petshop
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: petshop
    spec:
      containers:
      - image: petshop
        name: 873330726955.dkr.ecr.us-east-1.amazonaws.com/petshop-image:TAG
        ports:
        - containerPort: 8080
        resources: {}
status: {}
