apiVersion: apps/v1
kind: Deployment
metadata:
  name: petshop
spec:
  selector:
    matchLabels:
      app: petshop
  replicas: 3 
  template: 
    metadata:
      labels:
        app: petshop
    spec:
      containers:
      - name: petshop
        image: 873330726955.dkr.ecr.us-east-1.amazonaws.com/petshop-image:TAG
        ports:
        - containerPort: 8080
        imagePullPolicy: Always